_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.13.2
        t:
            "1":
                - 55
                - 105
            "2":
                - 55
                - 105
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.13.2
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
n_feature_t:
    value: 3
